# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AirQuality(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id_air_quality=None, amount=None, date=None):  # noqa: E501
        """AirQuality - a model defined in OpenAPI

        :param id_air_quality: The id_air_quality of this AirQuality.  # noqa: E501
        :type id_air_quality: int
        :param amount: The amount of this AirQuality.  # noqa: E501
        :type amount: float
        :param date: The date of this AirQuality.  # noqa: E501
        :type date: str
        """
        self.openapi_types = {
            'id_air_quality': int,
            'amount': float,
            'date': str
        }

        self.attribute_map = {
            'id_air_quality': 'idAirQuality',
            'amount': 'amount',
            'date': 'date'
        }

        self._id_air_quality = id_air_quality
        self._amount = amount
        self._date = date

    @classmethod
    def from_dict(cls, dikt) -> 'AirQuality':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AirQuality of this AirQuality.  # noqa: E501
        :rtype: AirQuality
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_air_quality(self):
        """Gets the id_air_quality of this AirQuality.


        :return: The id_air_quality of this AirQuality.
        :rtype: int
        """
        return self._id_air_quality

    @id_air_quality.setter
    def id_air_quality(self, id_air_quality):
        """Sets the id_air_quality of this AirQuality.


        :param id_air_quality: The id_air_quality of this AirQuality.
        :type id_air_quality: int
        """

        self._id_air_quality = id_air_quality

    @property
    def amount(self):
        """Gets the amount of this AirQuality.


        :return: The amount of this AirQuality.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this AirQuality.


        :param amount: The amount of this AirQuality.
        :type amount: float
        """

        self._amount = amount

    @property
    def date(self):
        """Gets the date of this AirQuality.


        :return: The date of this AirQuality.
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this AirQuality.


        :param date: The date of this AirQuality.
        :type date: str
        """

        self._date = date
