# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ..models.base_model_ import Model
from .. import util


class Temperature(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id_temperature=None, amount=None, date=None):  # noqa: E501
        """Temperature - a model defined in OpenAPI

        :param id_temperature: The id_temperature of this Temperature.  # noqa: E501
        :type id_temperature: int
        :param amount: The amount of this Temperature.  # noqa: E501
        :type amount: float
        :param date: The date of this Temperature.  # noqa: E501
        :type date: str
        """
        self.openapi_types = {
            'id_temperature': int,
            'amount': float,
            'date': str
        }

        self.attribute_map = {
            'id_temperature': 'idTemperature',
            'amount': 'amount',
            'date': 'date'
        }

        self._id_temperature = id_temperature
        self._amount = amount
        self._date = date

    @classmethod
    def from_dict(cls, dikt) -> 'Temperature':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Temperature of this Temperature.  # noqa: E501
        :rtype: Temperature
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_temperature(self):
        """Gets the id_temperature of this Temperature.


        :return: The id_temperature of this Temperature.
        :rtype: int
        """
        return self._id_temperature

    @id_temperature.setter
    def id_temperature(self, id_temperature):
        """Sets the id_temperature of this Temperature.


        :param id_temperature: The id_temperature of this Temperature.
        :type id_temperature: int
        """

        self._id_temperature = id_temperature

    @property
    def amount(self):
        """Gets the amount of this Temperature.


        :return: The amount of this Temperature.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this Temperature.


        :param amount: The amount of this Temperature.
        :type amount: float
        """

        self._amount = amount

    @property
    def date(self):
        """Gets the date of this Temperature.


        :return: The date of this Temperature.
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this Temperature.


        :param date: The date of this Temperature.
        :type date: str
        """

        self._date = date
